[package]
name = "bus_history"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_http = "1.0.0"

tokio = { version = "1", features = ["macros"] }
core = { path = "../../core" }
serde_json = "1.0.149"
